export const W=1100,H=620;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
export function createGame(){const g={players:[],ball:{x:550,y:310,vx:0,vy:0,owner:1,lock:0,shot:false,last:0},selected:1,score:[0,0],time:180,shotClock:30,phase:'ready',message:'Take the pool',charge:0,cooldown:0,elapsed:0,resetIn:0,aim:null};resetFormation(g,0);return g;}
export function resetFormation(g,team){g.players=[];for(let t=0;t<2;t++)for(let i=0;i<5;i++){const x=i===0?65:[420,310,280,390][i-1];g.players.push({id:t*5+i,team:t,keeper:i===0,x:t?W-x:x,y:i===0?310:[310,150,465,480][i-1],vx:0,vy:0,held:0});}g.ball={x:team?680:420,y:310,vx:0,vy:0,owner:team*5+1,lock:.4,shot:false,last:team};g.selected=1;g.shotClock=30;g.charge=0;}
export function switchPlayer(g){const candidates=g.players.filter(p=>p.team===0&&!p.keeper&&p.id!==g.selected);candidates.sort((a,b)=>distance(a,g.ball)-distance(b,g.ball));g.selected=candidates[0].id;}
function possess(g,p){if(g.ball.last!==p.team)g.shotClock=30;g.ball.owner=p.id;g.ball.last=p.team;g.ball.shot=false;g.ball.vx=0;g.ball.vy=0;p.held=0;if(p.team===0&&!p.keeper)g.selected=p.id;}
export function release(g,kind,power=.5){const p=g.players[g.ball.owner];if(!p||g.phase!=='playing')return;let target;if(kind==='pass'){const mates=g.players.filter(q=>q.team===p.team&&q.id!==p.id&&!q.keeper);target=mates.sort((a,b)=>{const cost=q=>distance(p,q)+(g.aim&&p.team===0?distance(q,g.aim)*.8:((p.team===0?-q.x:q.x)*.35));return cost(a)-cost(b);})[0];}else target=p.team===0?(g.aim||{x:W+20,y:clamp(p.y,245,375)}):{x:-20,y:310+(Math.sin(g.elapsed*2)*65)};let dx=target.x-p.x,dy=target.y-p.y;const d=Math.hypot(dx,dy)||1,speed=kind==='pass'?460:530+power*400;g.ball={x:p.x+dx/d*25,y:p.y+dy/d*25,vx:dx/d*speed,vy:dy/d*speed,owner:null,source:p.id,lock:.11,shot:kind!=='pass',last:p.team};g.charge=0;}
export function tackle(g){if(g.cooldown>0||g.phase!=='playing')return;g.cooldown=.7;const p=g.players[g.selected],owner=g.players[g.ball.owner];if(owner&&owner.team!==0&&distance(p,owner)<49){possess(g,p);g.message='Steal!';}}
function move(p,x,y,speed,dt){let dx=x-p.x,dy=y-p.y,d=Math.hypot(dx,dy);const step=Math.min(d,speed*dt);p.vx=d>1?dx/d*speed:0;p.vy=d>1?dy/d*speed:0;if(d){p.x+=dx/d*step;p.y+=dy/d*step;}p.x=clamp(p.x,30,W-30);p.y=clamp(p.y,32,H-32);}
export function step(g,dt,input={}){if(g.phase!=='playing')return;dt=Math.min(dt,.033);g.elapsed+=dt;g.time=Math.max(0,g.time-dt);g.cooldown=Math.max(0,g.cooldown-dt);g.ball.lock=Math.max(0,g.ball.lock-dt);if(g.time<=0){g.phase='ended';g.message=g.score[0]===g.score[1]?'A hard-fought draw':g.score[0]>g.score[1]?'You win!':'CPU wins';return;}if(g.resetIn>0){g.resetIn-=dt;if(g.resetIn<=0){resetFormation(g,g.kickoff);g.message=g.kickoff?'CPU possession':'Your possession';}return;}g.shotClock-=dt;if(g.shotClock<=0){const t=1-g.ball.last;resetFormation(g,t);g.message='Shot clock · possession changed';return;}const owner=g.players[g.ball.owner];if(input.charge&&owner?.team===0&&owner.id===g.selected)g.charge=Math.min(1,g.charge+dt*.85);
for(const p of g.players){const dir=p.team===0?1:-1,ours=owner?.team===p.team;if(p.keeper){move(p,p.team===0?55:W-55,clamp(g.ball.y,225,395),155,dt);if(owner===p){p.held+=dt;if(p.held>.5)release(g,'pass');}continue;}if(p.team===0&&p.id===g.selected){const dx=input.x||0,dy=input.y||0,n=Math.hypot(dx,dy)||1;move(p,p.x+dx/n*100,p.y+dy/n*100,owner===p?133:164,dt);continue;}if(owner===p){p.held+=dt;move(p,p.team===0?850:220,310+Math.sin(g.elapsed+p.id)*95,112,dt);if(p.team===1){if((p.x<350&&p.held>1.1)||p.held>5)release(g,'shot',.55);else if(p.held>1.6&&g.players.some(q=>q.team!==p.team&&distance(q,p)<65))release(g,'pass');}continue;}let tx,ty;if(!owner){tx=g.ball.x;ty=g.ball.y;}else if(ours){const i=p.id%5;tx=clamp(owner.x+dir*(i===2?110:-90),150,950);ty=[310,310,130,480,385][i];}else{const defenders=g.players.filter(q=>q.team===p.team&&!q.keeper).sort((a,b)=>distance(a,owner)-distance(b,owner));if(defenders[0]===p){tx=owner.x;ty=owner.y;if(p.team===1&&distance(p,owner)<30&&owner.held>1.1){possess(g,p);g.message='CPU steals possession';}}else{const mark=g.players[(1-p.team)*5+(p.id%5)];tx=mark.x-dir*52;ty=mark.y;}}move(p,tx,ty,ours?119:126,dt);}
if(owner?.team===0)owner.held+=dt;
// Keep swimmers apart while allowing close marking and tackles.
for(let i=0;i<g.players.length;i++)for(let j=i+1;j<g.players.length;j++){const a=g.players[i],b=g.players[j],d=distance(a,b);if(d>0&&d<27){const push=(27-d)*.5;a.x+=(a.x-b.x)/d*push;a.y+=(a.y-b.y)/d*push;b.x-=(a.x-b.x)/d*push;b.y-=(a.y-b.y)/d*push;}}
const b=g.ball,carrier=g.players[b.owner];if(carrier){b.x=carrier.x+(carrier.team===0?19:-19);b.y=carrier.y-6;return;}
// Substeps prevent fast shots passing through the goalkeeper.
for(let n=0;n<4;n++){b.x+=b.vx*dt/4;b.y+=b.vy*dt/4;if(b.y<12||b.y>H-12){b.y=clamp(b.y,12,H-12);b.vy*=-.7;}if(b.x<8||b.x>W-8){if(b.y>218&&b.y<402){const team=b.x>W/2?0:1;g.score[team]++;g.message=team===0?'GOAL · Blue Tide!':'GOAL · Red Current';g.resetIn=2;g.kickoff=1-team;return;}b.x=clamp(b.x,8,W-8);b.vx*=-.65;}{for(const p of g.players){if(b.lock>0&&p.id===b.source)continue;const radius=p.keeper?25:18;if(distance(b,p)<radius){if(b.shot&&!p.keeper&&p.team===b.last)continue;possess(g,p);g.message=p.keeper?'Goalkeeper save':p.team===0?'Your possession':'CPU possession';return;}}}}
const friction=Math.pow(b.shot?.993:.985,dt*60);b.vx*=friction;b.vy*=friction;}
