'use client';
import {useEffect,useRef,useState} from 'react';
import TouchControls,{type TouchInput} from './touch-controls';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import type {CameraMode} from './scene-3d';
import {createGame,step,release,switchPlayer,tackle,W,H,TEAM_SIZE,PERIOD_SECONDS} from './engine.mjs';

export default function Home(){const canvas=useRef<HTMLCanvasElement>(null),game=useRef<any>(null),keys=useRef(new Set<string>()),scene=useRef<ReturnType<typeof import('./scene-3d').createPoolScene>|null>(null),touch=useRef<TouchInput>({x:0,y:0,charge:false});const [hud,setHud]=useState({score:[0,0],time:PERIOD_SECONDS,period:1,clock:28,phase:'ready',message:'Take the pool',selected:2,charge:0,owner:0,hasBall:true});const [cameraMode,setCameraMode]=useState<CameraMode>('overhead'),[ready,setReady]=useState(false),[error,setError]=useState('');
useEffect(()=>{const g=createGame();game.current=g;const c=canvas.current!;let cancelled=false;import('./scene-3d').then(({createPoolScene})=>{if(cancelled)return;try{scene.current=createPoolScene(c);setReady(true);}catch{setError('3D needs WebGL support. Try a current browser with hardware acceleration enabled.');}}).catch(()=>setError('The 3D view could not load. Reload to try again.'));const contextLost=(e:Event)=>{e.preventDefault();g.phase='paused';setError('The 3D view was interrupted. Reload to resume playing.');};c.addEventListener('webglcontextlost',contextLost);let frame=0,last=0,ui=0;const sync=()=>setHud({score:[...g.score],time:g.time,period:g.period,clock:g.shotClock,phase:g.phase,message:g.message,selected:g.selected%TEAM_SIZE+1,charge:g.charge,owner:g.ball.last,hasBall:g.ball.owner===g.selected});
const down=(e:KeyboardEvent)=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();if(e.repeat)return;const k=e.key.toLowerCase();keys.current.add(k);if(k==='enter'&&g.phase==='ready'&&scene.current)g.phase='playing';if(k==='p'||k==='escape'){if(g.phase==='playing')g.phase='paused';else if(g.phase==='paused')g.phase='playing';}if(g.phase==='playing'){if(k==='q')switchPlayer(g);if(k==='e'&&g.ball.owner===g.selected)release(g,'pass');if(k==='f')tackle(g);}sync();};const up=(e:KeyboardEvent)=>{const k=e.key.toLowerCase();keys.current.delete(k);if(k===' '&&g.ball.owner===g.selected)release(g,'shot',g.charge);};const blur=()=>{keys.current.clear();Object.assign(touch.current,{x:0,y:0,charge:false});g.charge=0;if(g.phase==='playing')g.phase='paused';sync();};const visibility=()=>{if(document.hidden)blur();};document.addEventListener('visibilitychange',visibility);window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);
const loop=(t:number)=>{const dt=last?Math.min((t-last)/1000,.033):0;last=t;const k=keys.current;if(g.phase!=='playing'){Object.assign(touch.current,{x:0,y:0,charge:false});g.charge=0;}const input=scene.current?.movement(touch.current.x+Number(k.has('d')||k.has('arrowright'))-Number(k.has('a')||k.has('arrowleft')),touch.current.y+Number(k.has('s')||k.has('arrowdown'))-Number(k.has('w')||k.has('arrowup')))||{x:0,y:0};if(scene.current){step(g,dt,{...input,charge:k.has(' ')||touch.current.charge});scene.current.update(g);}if(t-ui>100){sync();ui=t;}frame=requestAnimationFrame(loop);};frame=requestAnimationFrame(loop);return()=>{cancelled=true;scene.current?.dispose();scene.current=null;c.removeEventListener('webglcontextlost',contextLost);cancelAnimationFrame(frame);document.removeEventListener('visibilitychange',visibility);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);};},[]);
function start(){if(!game.current||!ready||error)return;if(game.current.phase==='ended')Object.assign(game.current,createGame());game.current.phase='playing';keys.current.clear();Object.assign(touch.current,{x:0,y:0,charge:false});}
function restart(){if(!game.current||!ready||error)return;Object.assign(game.current,createGame());game.current.phase='playing';keys.current.clear();Object.assign(touch.current,{x:0,y:0,charge:false});}
const fmt=(n:number)=>`${Math.floor(Math.ceil(n)/60)}:${String(Math.ceil(n)%60).padStart(2,'0')}`;
return <main className={hud.phase==='playing'?'is-playing':''}><header><div className="brand"><span className="brandmark">≈</span><div><h1>POOL / PLAY</h1><p>Water polo · 3D quick match</p></div></div><div className="header-actions"><div className="camera-picker"><Select disabled={!ready} value={cameraMode} onValueChange={value=>{if(value){setCameraMode(value as CameraMode);scene.current?.setCamera(value as CameraMode);}}}><SelectTrigger aria-label="Camera angle"><SelectValue>{cameraMode==='overhead'?'Overhead':cameraMode==='broadcast'?'Broadcast':'End-line'}</SelectValue></SelectTrigger><SelectContent className="camera-menu"><SelectItem value="overhead">Overhead</SelectItem><SelectItem value="broadcast">Broadcast</SelectItem><SelectItem value="endline">End-line</SelectItem></SelectContent></Select></div><button onClick={()=>{if(game.current?.phase==='playing')game.current.phase='paused';else if(game.current?.phase==='paused')start();}}>{hud.phase==='paused'?'Resume':'Pause'} <kbd>P</kbd></button><button onClick={restart} aria-label="Restart match">↻ <span>Restart</span></button></div></header>
<section className="arena" aria-label="Water polo game"><div className="scoreboard"><div className="team home"><span className="team-dot"/><div><strong>BLUE TIDE</strong><small>Your team</small></div><b>{hud.score[0]}</b></div><div className="match-time"><span>QUARTER {hud.period} / 4</span><strong>{fmt(hud.time)}</strong></div><div className="team away"><b>{hud.score[1]}</b><div><strong>RED CURRENT</strong><small>CPU team</small></div><span className="team-dot"/></div></div>
<div className="pool-wrap"><canvas ref={canvas} width={W} height={H} aria-label="3D water polo pool. Control Blue Tide and attack the red end." onPointerMove={e=>{if(e.pointerType!=='mouse')return;const point=scene.current?.point(e.clientX,e.clientY);if(game.current&&point)game.current.aim=point;}} onPointerLeave={e=>{if(e.pointerType==='mouse'&&game.current)game.current.aim=null;}} />
{!error&&hud.phase!=='playing'&&<div className="overlay"><div className="start-panel"><span className="eyebrow">{hud.phase==='ready'?'WELCOME TO THE POOL':hud.phase==='paused'?'TIME OUT':'FULL TIME'}</span><h2>{hud.phase==='ready'?'Make a splash.':hud.phase==='paused'?'Catch your breath.':hud.message}</h2><p>{hud.phase==='ready'?'You’re Blue Tide. Swim, pass, and find the right corner. Four quick quarters. Six teammates. Make the next pass count.':hud.phase==='paused'?'Your match is paused. Jump back in when you’re ready.':`${hud.score[0]} – ${hud.score[1]} · Ready for a rematch?`}</p><button className="primary" disabled={!ready} onClick={start}>{!ready?'Loading 3D pool…':hud.phase==='ready'?'Start match':hud.phase==='paused'?'Back to the pool':'Play again'} <span>→</span></button>{hud.phase==='ready'&&<small className="keyboard-hint">WASD to swim · Hold SPACE to shoot</small>}</div></div>}
{error&&<div className="overlay"><div className="start-panel"><h2>3D view unavailable</h2><p>{error}</p><button className="primary" onClick={()=>window.location.reload()}>Reload game</button></div></div>}{hud.phase==='playing'&&game.current?.resetIn>0&&<div className="goal-flash">{hud.message}</div>}</div>
<div className="match-strip"><div><span className="live-dot"/>{hud.phase==='playing'?hud.message:hud.phase==='ready'?'Ready for the opening possession':hud.phase==='paused'?'Match paused':'Match complete'}</div><span>ATTACK THE RED END</span><div><span className="shot-label">SHOT CLOCK</span><b className={hud.clock<6?'urgent':''}>{Math.ceil(hud.clock)}s</b></div></div></section>
<footer><div className="controls-title"><strong>In your hands</strong><span>Selected swimmer <b>#{hud.selected}</b></span></div><div className="control"><div><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd></div><span>Swim <small>or arrow keys</small></span></div><div className="control"><kbd>Q</kbd><span>Switch player</span></div><div className="control"><kbd>E</kbd><span>Pass <small>toward pointer</small></span></div><div className="control"><kbd>SPACE</kbd><span>Hold & release to shoot <small>move pointer to aim</small></span></div><div className="control"><kbd>F</kbd><span>Steal <small>get close first</small></span></div></footer>
<TouchControls input={touch} active={hud.phase==='playing'&&ready&&!error} hasBall={hud.hasBall} charge={hud.charge} onSwitch={()=>{if(game.current?.phase==='playing'){game.current.charge=0;touch.current.charge=false;switchPlayer(game.current);}}} onPass={()=>{const g=game.current;if(g?.phase==='playing'&&g.ball.owner===g.selected){g.aim=null;release(g,'pass');touch.current.charge=false;}}} onSteal={()=>game.current&&tackle(game.current)} onShoot={()=>{const g=game.current;if(g?.ball.owner===g?.selected)release(g,'shot',g.charge);}} onCancel={()=>{if(game.current)game.current.charge=0;}} onAim={point=>{if(game.current)game.current.aim=point;}} />
<p className="mobile-tip">Use both thumbs. Turn your phone sideways for a larger pool.</p>
<p className="pool-note">Six field players + a goalkeeper. Four 90-second quarters · 28-second possession · 18-second rebound clock.</p><details className="rules-note"><summary>Rules & inspiration</summary><p>Based on World Aquatics rules: seven-a-side teams, a 25 × 20 m pool, a 3 m goal, 28-second possession, 18-second attacking rebounds, goal-area restrictions, free throws after infringements, and conceding-team restarts.</p><p>Quick-match adaptations: 90-second quarters, alternating starting possession, fixed attacking ends, automatic goalkeeper throws, simplified steals, and draws at full time. Exclusions, penalty fouls, swim-offs and manual substitutions are not simulated.</p><p>Your earlier water polo prototype inspired the curved attacking formation, swimmer acceleration, and seven-a-side setup.</p><a href="https://www.worldaquatics.com/rules/competition-regulations" target="_blank" rel="noreferrer">World Aquatics competition regulations ↗</a></details></main>;
}
