'use client';
import {useEffect,useRef,useState} from 'react';
import {createGame,step,release,switchPlayer,tackle,W,H} from './engine.mjs';

function draw(ctx:CanvasRenderingContext2D,g:any){
ctx.clearRect(0,0,W,H);const grad=ctx.createLinearGradient(0,0,W,H);grad.addColorStop(0,'#087f99');grad.addColorStop(1,'#095774');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);
ctx.strokeStyle='#ffffff08';ctx.lineWidth=1;for(let x=0;x<W;x+=35){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke();}for(let y=0;y<H;y+=35){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke();}
ctx.strokeStyle='#d5ffff55';ctx.lineWidth=2;ctx.strokeRect(15,15,W-30,H-30);ctx.setLineDash([8,9]);ctx.beginPath();ctx.moveTo(W/2,15);ctx.lineTo(W/2,H-15);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.arc(W/2,H/2,69,0,Math.PI*2);ctx.stroke();
for(const x of [150,W-150]){ctx.strokeStyle='#ffcc6260';ctx.beginPath();ctx.moveTo(x,16);ctx.lineTo(x,H-16);ctx.stroke();}for(const x of [65,W-65]){ctx.strokeStyle='#ff777966';ctx.beginPath();ctx.moveTo(x,16);ctx.lineTo(x,H-16);ctx.stroke();}
for(const x of [0,W-24]){ctx.fillStyle='#082b40';ctx.fillRect(x,218,24,184);ctx.strokeStyle='#ffffff35';ctx.lineWidth=1;for(let y=218;y<402;y+=12){ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+24,y);ctx.stroke();}ctx.strokeStyle='#ecffff';ctx.lineWidth=5;ctx.strokeRect(x,218,24,184);}
ctx.font='600 13px sans-serif';ctx.fillStyle='#b3efff80';ctx.textAlign='center';ctx.fillText('BLUE TIDE',110,50);ctx.fillText('RED CURRENT',W-115,50);
for(const p of g.players){const moving=Math.hypot(p.vx,p.vy)>2;ctx.strokeStyle='#b7efff30';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(p.x,p.y+6,25+(moving?Math.sin(g.elapsed*12+p.id)*4:0),18,0,0,Math.PI*2);ctx.stroke();if(p.id===g.selected){ctx.strokeStyle='#e1ff83';ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,27,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#e1ff83';ctx.beginPath();ctx.moveTo(p.x,p.y-32);ctx.lineTo(p.x-5,p.y-40);ctx.lineTo(p.x+5,p.y-40);ctx.fill();}ctx.fillStyle='#00283866';ctx.beginPath();ctx.arc(p.x+2,p.y+5,18,0,Math.PI*2);ctx.fill();ctx.fillStyle=p.keeper?'#ffd477':p.team===0?'#e9faff':'#ff776e';ctx.beginPath();ctx.arc(p.x,p.y,16,0,Math.PI*2);ctx.fill();ctx.strokeStyle=p.team===0?'#a5dbe9':'#d94f4a';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle=p.team===0?'#16495d':'#612528';ctx.font='bold 14px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(p.keeper?'G':String(p.id%5+1),p.x,p.y+1);}
const p=g.players[g.selected];if(g.ball.owner===p.id){const aim=g.aim||{x:W+20,y:Math.max(245,Math.min(375,p.y))},d=Math.hypot(aim.x-p.x,aim.y-p.y);ctx.strokeStyle='#e1ff8390';ctx.lineWidth=2;ctx.setLineDash([5,7]);ctx.beginPath();ctx.moveTo(p.x+30*(aim.x-p.x)/d,p.y+30*(aim.y-p.y)/d);ctx.lineTo(p.x+110*(aim.x-p.x)/d,p.y+110*(aim.y-p.y)/d);ctx.stroke();ctx.setLineDash([]);if(g.charge){ctx.strokeStyle='#e1ff83';ctx.lineWidth=5;ctx.beginPath();ctx.arc(p.x,p.y,32,-Math.PI/2,-Math.PI/2+Math.PI*2*g.charge);ctx.stroke();}}
ctx.fillStyle='#002e4866';ctx.beginPath();ctx.arc(g.ball.x+3,g.ball.y+4,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffdc57';ctx.beginPath();ctx.arc(g.ball.x,g.ball.y,9,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ac7c1e';ctx.lineWidth=1.5;ctx.stroke();ctx.beginPath();ctx.moveTo(g.ball.x-7,g.ball.y-4);ctx.quadraticCurveTo(g.ball.x+2,g.ball.y+1,g.ball.x+7,g.ball.y-4);ctx.stroke();
}
export default function Home(){const canvas=useRef<HTMLCanvasElement>(null),game=useRef<any>(null),keys=useRef(new Set<string>());const [hud,setHud]=useState({score:[0,0],time:180,clock:30,phase:'ready',message:'Take the pool',selected:2,charge:0,owner:0});
useEffect(()=>{const g=createGame();game.current=g;const c=canvas.current!,ctx=c.getContext('2d')!;let frame=0,last=0,ui=0;const sync=()=>setHud({score:[...g.score],time:g.time,clock:g.shotClock,phase:g.phase,message:g.message,selected:g.selected%5+1,charge:g.charge,owner:g.ball.last});
const down=(e:KeyboardEvent)=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','Tab'].includes(e.key))e.preventDefault();if(e.repeat)return;const k=e.key.toLowerCase();keys.current.add(k);if(k==='enter'&&g.phase==='ready')g.phase='playing';if(k==='p'||k==='escape'){if(g.phase==='playing')g.phase='paused';else if(g.phase==='paused')g.phase='playing';}if(g.phase==='playing'){if(k==='q'||k==='tab')switchPlayer(g);if(k==='e'&&g.ball.owner===g.selected)release(g,'pass');if(k==='f')tackle(g);}sync();};const up=(e:KeyboardEvent)=>{const k=e.key.toLowerCase();keys.current.delete(k);if(k===' '&&g.ball.owner===g.selected)release(g,'shot',g.charge);};const blur=()=>{keys.current.clear();g.charge=0;if(g.phase==='playing')g.phase='paused';sync();};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);
const loop=(t:number)=>{const dt=last?Math.min((t-last)/1000,.033):0;last=t;const k=keys.current;step(g,dt,{x:Number(k.has('d')||k.has('arrowright'))-Number(k.has('a')||k.has('arrowleft')),y:Number(k.has('s')||k.has('arrowdown'))-Number(k.has('w')||k.has('arrowup')),charge:k.has(' ')});draw(ctx,g);if(t-ui>100){sync();ui=t;}frame=requestAnimationFrame(loop);};frame=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(frame);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);};},[]);
function start(){if(!game.current)return;if(game.current.phase==='ended')Object.assign(game.current,createGame());game.current.phase='playing';keys.current.clear();}
function restart(){Object.assign(game.current,createGame());game.current.phase='playing';keys.current.clear();}
const fmt=(n:number)=>`${Math.floor(Math.ceil(n)/60)}:${String(Math.ceil(n)%60).padStart(2,'0')}`;
return <main><header><div className="brand"><span className="brandmark">≈</span><div><h1>POOL / PLAY</h1><p>Water polo · arcade match</p></div></div><div className="header-actions"><span className="local">YOU VS CPU</span><button onClick={()=>{if(game.current?.phase==='playing')game.current.phase='paused';else if(game.current?.phase==='paused')start();}}>{hud.phase==='paused'?'Resume':'Pause'} <kbd>P</kbd></button><button onClick={restart} aria-label="Restart match">↻ <span>Restart</span></button></div></header>
<section className="arena" aria-label="Water polo game"><div className="scoreboard"><div className="team home"><span className="team-dot"/><div><strong>BLUE TIDE</strong><small>Your team</small></div><b>{hud.score[0]}</b></div><div className="match-time"><span>3-MINUTE MATCH</span><strong>{fmt(hud.time)}</strong></div><div className="team away"><b>{hud.score[1]}</b><div><strong>RED CURRENT</strong><small>CPU team</small></div><span className="team-dot"/></div></div>
<div className="pool-wrap"><canvas ref={canvas} width={W} height={H} aria-label="Top-down water polo pool. Control Blue Tide and attack the goal on the right." onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();if(game.current)game.current.aim={x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H};}} onPointerLeave={()=>{if(game.current)game.current.aim=null;}} />
{hud.phase!=='playing'&&<div className="overlay"><div className="start-panel"><span className="eyebrow">{hud.phase==='ready'?'WELCOME TO THE POOL':hud.phase==='paused'?'TIME OUT':'FULL TIME'}</span><h2>{hud.phase==='ready'?'Make a splash.':hud.phase==='paused'?'Catch your breath.':hud.message}</h2><p>{hud.phase==='ready'?'You’re Blue Tide. Swim, pass, and find the right corner. Three minutes on the clock.':hud.phase==='paused'?'Your match is paused. Jump back in when you’re ready.':`${hud.score[0]} – ${hud.score[1]} · Ready for a rematch?`}</p><button className="primary" onClick={start}>{hud.phase==='ready'?'Start match':hud.phase==='paused'?'Back to the pool':'Play again'} <span>→</span></button>{hud.phase==='ready'&&<small>WASD to swim · Hold SPACE to shoot</small>}</div></div>}
{hud.phase==='playing'&&game.current?.resetIn>0&&<div className="goal-flash">{hud.message}</div>}</div>
<div className="match-strip"><div><span className="live-dot"/>{hud.phase==='playing'?hud.message:hud.phase==='ready'?'Ready for the opening possession':hud.phase==='paused'?'Match paused':'Match complete'}</div><span>ATTACK RIGHT →</span><div><span className="shot-label">SHOT CLOCK</span><b className={hud.clock<6?'urgent':''}>{Math.ceil(hud.clock)}s</b></div></div></section>
<footer><div className="controls-title"><strong>In your hands</strong><span>Selected swimmer <b>#{hud.selected}</b></span></div><div className="control"><div><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd></div><span>Swim <small>or arrow keys</small></span></div><div className="control"><kbd>Q</kbd><span>Switch player</span></div><div className="control"><kbd>E</kbd><span>Pass <small>toward pointer</small></span></div><div className="control"><kbd>SPACE</kbd><span>Hold & release to shoot <small>move pointer to aim</small></span></div><div className="control"><kbd>F</kbd><span>Steal <small>get close first</small></span></div></footer>
<div className="touch-controls" aria-label="Touch controls"><div>{[['↑','w'],['←','a'],['↓','s'],['→','d']].map(([label,key])=><button key={key} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);keys.current.add(key);}} onPointerUp={()=>keys.current.delete(key)} onPointerCancel={()=>keys.current.delete(key)}>{label}</button>)}</div><div><button onClick={()=>switchPlayer(game.current)}>Switch</button><button onClick={()=>game.current.ball.owner===game.current.selected&&release(game.current,'pass')}>Pass</button><button onClick={()=>game.current.ball.owner===game.current.selected?release(game.current,'shot',.7):tackle(game.current)}>Shoot / steal</button></div></div>
<p className="pool-note">Four field players + a goalkeeper per team. Pass into space, beat the keeper, and score before the 30-second shot clock runs out.</p></main>;
}
