'use client';
import {useEffect,useRef,useState,type MutableRefObject,type PointerEvent} from 'react';
import {stickVector,shotTarget} from './touch-input.mjs';
export type TouchInput={x:number;y:number;charge:boolean};
export default function TouchControls({input,active,hasBall,charge,onSwitch,onPass,onSteal,onShoot,onAim,onCancel}:{input:MutableRefObject<TouchInput>;active:boolean;hasBall:boolean;charge:number;onSwitch:()=>void;onPass:()=>void;onSteal:()=>void;onShoot:()=>void;onCancel:()=>void;onAim:(point:{x:number;y:number})=>void}){
const stick=useRef<number|null>(null),shot=useRef<{id:number;y:number}|null>(null),[knob,setKnob]=useState({x:0,y:0});
useEffect(()=>{if(!active){stick.current=null;shot.current=null;setKnob({x:0,y:0});}},[active]);
function move(e:PointerEvent<HTMLDivElement>){if(stick.current!==e.pointerId)return;const r=e.currentTarget.getBoundingClientRect(),v=stickVector(e.clientX-r.left-r.width/2,e.clientY-r.top-r.height/2);input.current.x=v.x;input.current.y=v.y;setKnob({x:v.x*35,y:v.y*35});}
function stop(){stick.current=null;input.current.x=0;input.current.y=0;setKnob({x:0,y:0});}
function finish(e:PointerEvent<HTMLButtonElement>,fire:boolean){if(shot.current?.id!==e.pointerId)return;const charged=input.current.charge;shot.current=null;input.current.charge=false;if(fire&&active&&charged)onShoot();else onCancel();}
return <section className="touch-controls" aria-label="Touch game controls"><div className="swim-control"><div className="joystick" role="group" aria-label="Drag to swim in any direction" onPointerDown={e=>{if(!active||stick.current!==null)return;e.preventDefault();stick.current=e.pointerId;e.currentTarget.setPointerCapture(e.pointerId);move(e);}} onPointerMove={move} onPointerUp={stop} onPointerCancel={stop} onLostPointerCapture={stop}><span className="stick-guides" aria-hidden="true">↑<br/>← · →<br/>↓</span><span className="stick-knob" style={{transform:`translate(${active?knob.x:0}px,${active?knob.y:0}px)`}}/></div><span className="touch-caption">Drag to swim</span></div><div className="touch-actions"><div className="touch-secondary"><button disabled={!active} onClick={onSwitch}>Switch</button><button disabled={!active||!hasBall} onClick={onPass}>Pass</button></div><button className="shoot-button" disabled={!active} onPointerDown={e=>{if(!active||shot.current)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);if(!hasBall){onSteal();return;}shot.current={id:e.pointerId,y:e.clientY};onAim(shotTarget(0));input.current.charge=true;}} onPointerMove={e=>{if(shot.current?.id===e.pointerId)onAim(shotTarget(e.clientY-shot.current.y));}} onPointerUp={e=>finish(e,true)} onPointerCancel={e=>finish(e,false)} onLostPointerCapture={e=>finish(e,false)} onContextMenu={e=>e.preventDefault()}><span className="charge-fill" style={{width:`${charge*100}%`}}/><span>{hasBall?'Hold to shoot':'Steal'}</span></button><span className="touch-caption">{hasBall?'Slide ↑ ↓ to aim · release to shoot':'Get close to the ball carrier'}</span></div></section>;
}
